version: '3'

vars:
  TODO_TASKER_DB_DSN: '{{.TODO_TASKER_DB_DSN | default ""}}'

# Note: Run tasks from the backend directory, or use 'task -f backend/Taskfile.yaml <task>'
# On Windows/cmd: set TODO_TASKER_DB_DSN=<dsn> && task migrations:new name=<name>
# On Windows/PowerShell: $env:TODO_TASKER_DB_DSN = '<dsn>'; task migrations:new name=<name>

tasks:
  help:
    desc: print this help message
    cmds:
    - task --list-all
    silent: true

  confirm:
    desc: confirmation prompt
    cmds:
    - |
      echo -n 'Are you sure? [y/N] ' && read ans && [ ${ans:-N} = y ]
    silent: true
    internal: true

  run:
    desc: run the cmd/go-TODO_TASKER application
    cmds:
    - go run ./cmd/go-TODO_TASKER

  migrations:new:
    desc: create a new database migration
    vars:
      NAME: '{{.name | default ""}}'
    cmds:
    - |
      if [ -z "{{.NAME}}" ]; then
        echo "Error: name parameter is required"
        echo "Usage: task migrations:new name=migration_name"
        exit 1
      fi
    - echo 'Creating migration file for {{.NAME}}...'
    - tern new -m ./internal/database/migrations {{.NAME}}

  migrations:up:
    desc: apply all up database migrations
    deps: [ confirm ]
    cmds:
    - echo 'Running up migrations...'
    - tern migrate -m ./internal/database/migrations --conn-string {{.TODO_TASKER_DB_DSN}}

  tidy:
    desc: format all .go files, and tidy and vendor module dependencies
    cmds:
    - echo 'Formatting .go files...'
    - go fmt ./...
    - echo 'Tidying module dependencies...'
    - go mod tidy
    - echo 'Verifying dependencies...'
    - go mod verify